#include "zcompiler/Lexer/Token.h"

using namespace llvm;

namespace zc {

StringRef getTokenKindName(TokenKind kind) {
  switch (kind) {
  case TokenKind::EndOfFile:
    return "eof";
  case TokenKind::Identifier:
    return "identifier";
  case TokenKind::Integer:
    return "integer";
  case TokenKind::KwFunc:
    return "kw_func";
  case TokenKind::KwLet:
    return "kw_let";
  case TokenKind::KwReturn:
    return "kw_return";
  case TokenKind::KwIf:
    return "kw_if";
  case TokenKind::KwElse:
    return "kw_else";
  case TokenKind::KwWhile:
    return "kw_while";
  case TokenKind::KwI32:
    return "kw_i32";
  case TokenKind::KwPtr:
    return "kw_ptr";
  case TokenKind::KwLoad:
    return "kw_load";
  case TokenKind::KwStore:
    return "kw_store";
  case TokenKind::KwPrintI32:
    return "kw_print_i32";
  case TokenKind::KwVectorAdd:
    return "kw_vector_add";
  case TokenKind::KwVectorCopy:
    return "kw_vector_copy";
  case TokenKind::KwVectorScale:
    return "kw_vector_scale";
  case TokenKind::KwVectorMul:
    return "kw_vector_mul";
  case TokenKind::KwVectorReduceAdd:
    return "kw_vector_reduce_add";
  case TokenKind::KwVectorSelectLT:
    return "kw_vector_select_lt";
  case TokenKind::KwVectorSelectLE:
    return "kw_vector_select_le";
  case TokenKind::KwVectorSelectGT:
    return "kw_vector_select_gt";
  case TokenKind::KwVectorSelectGE:
    return "kw_vector_select_ge";
  case TokenKind::KwVectorSelectEQ:
    return "kw_vector_select_eq";
  case TokenKind::KwVectorSelectNE:
    return "kw_vector_select_ne";
  case TokenKind::KwVectorSelectULT:
    return "kw_vector_select_ult";
  case TokenKind::KwVectorSelectULE:
    return "kw_vector_select_ule";
  case TokenKind::KwVectorSelectUGT:
    return "kw_vector_select_ugt";
  case TokenKind::KwVectorSelectUGE:
    return "kw_vector_select_uge";
  case TokenKind::KwVectorMaskLT:
    return "kw_vector_mask_lt";
  case TokenKind::KwVectorMaskLE:
    return "kw_vector_mask_le";
  case TokenKind::KwVectorMaskGT:
    return "kw_vector_mask_gt";
  case TokenKind::KwVectorMaskGE:
    return "kw_vector_mask_ge";
  case TokenKind::KwVectorMaskEQ:
    return "kw_vector_mask_eq";
  case TokenKind::KwVectorMaskNE:
    return "kw_vector_mask_ne";
  case TokenKind::KwVectorMaskULT:
    return "kw_vector_mask_ult";
  case TokenKind::KwVectorMaskULE:
    return "kw_vector_mask_ule";
  case TokenKind::KwVectorMaskUGT:
    return "kw_vector_mask_ugt";
  case TokenKind::KwVectorMaskUGE:
    return "kw_vector_mask_uge";
  case TokenKind::KwVectorMaskedAdd:
    return "kw_vector_masked_add";
  case TokenKind::KwVectorMaskedSub:
    return "kw_vector_masked_sub";
  case TokenKind::KwVectorMaskedMul:
    return "kw_vector_masked_mul";
  case TokenKind::KwVectorMaskedStore:
    return "kw_vector_masked_store";
  case TokenKind::KwVectorMaskedLoad:
    return "kw_vector_masked_load";
  case TokenKind::Plus:
    return "plus";
  case TokenKind::Minus:
    return "minus";
  case TokenKind::Star:
    return "star";
  case TokenKind::Slash:
    return "slash";
  case TokenKind::Equal:
    return "equal";
  case TokenKind::EqualEqual:
    return "equal_equal";
  case TokenKind::BangEqual:
    return "bang_equal";
  case TokenKind::Less:
    return "less";
  case TokenKind::LessEqual:
    return "less_equal";
  case TokenKind::Greater:
    return "greater";
  case TokenKind::GreaterEqual:
    return "greater_equal";
  case TokenKind::Arrow:
    return "arrow";
  case TokenKind::LParen:
    return "l_paren";
  case TokenKind::RParen:
    return "r_paren";
  case TokenKind::LBrace:
    return "l_brace";
  case TokenKind::RBrace:
    return "r_brace";
  case TokenKind::LBracket:
    return "l_bracket";
  case TokenKind::RBracket:
    return "r_bracket";
  case TokenKind::Colon:
    return "colon";
  case TokenKind::Comma:
    return "comma";
  case TokenKind::Semicolon:
    return "semicolon";
  }
  return "unknown";
}

} // namespace zc
